# Generated by Django 3.2.2 on 2021-05-12 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_question_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=280, unique=True),
            preserve_default=False,
        ),
    ]
