# Generated by Django 3.2.4 on 2021-07-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='catagories',
            new_name='categories',
        ),
    ]
