# Generated by Django 3.2.4 on 2021-07-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_catagories_question_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='submitted',
        ),
        migrations.AddField(
            model_name='question',
            name='original_author',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
